# y <- candidatos_receita_despesa %>% pull(despesa_total)
# x <- candidatos_receita_despesa %>% pull(receita_total)
# model <- lm(y~x)
# plot(y~x)
# abline(model)
# 
# ggplot(candidatos_receita_despesa, aes(despesa_total, receita_total)) + geom_point() + stat_smooth(method="lm", col="red")
situacao <- candidatos_receita_despesa_final %>% pull(DS_SIT_TOT_TURNO)
receita <- candidatos_receita_despesa_final %>% pull(receita_total)
despesa <- candidatos_receita_despesa_final %>% pull(despesa_total)
partido <- candidatos_receita_despesa_final %>% pull(SG_PARTIDO)
cargo <- candidatos_receita_despesa_final %>% pull(DS_CARGO)
modelo_receita <- lm(situacao~receita)
modelo_despesa <- lm(situacao~despesa)
modelo_partido <- lm(situacao~factor(partido))
modelo_cargo <- lm(situacao~factor(cargo))
modelo_total <- lm(situacao~receita+despesa+factor(partido)+factor(cargo))
